const products = [
{
    id: 0,
    name: "Drut spawalniczy Tysweld T20.003 5 kg",
    description: "Drut elektrodowy manganowo – krzemowy, miedziowany, przeznaczony do spawania metodą MIG/MAG stali niskowęglowych konstrukcyjnych oraz drobnoziarnistych stali węglowo manganowych.",
    category: "drut",
    price: 60.00,
    image: "./img/drut0-8.jpg",
    status: "Promocja",
    sale: true,
    saleAmount: 4, 
},
{
    id: 1,
    name: "Zacisk Rhinoweld GC17-00-00-600 600 A",
    description: "Solidny zacisk spawalniczy wykonany z grubego odlewu mosiężnego zapewnia dobre przewodzenie prądu. Odporny na uszkodzenia i uszczerbki mechaniczne. Dzięki zastosowaniu mosiądzu szerokość uchwytu jest zredukowana do minimum zachowując bardzo dobre przewodzenie prądu.",
    category: "zacisk",
    price: 50.00,
    image: "./img/zacisk17-600.jpg", 
},
{
    id: 2,
    name: "Zacisk Rhinoweld GC08-00-00-200 200 A",
    description: "Zacisk kleszczowy zapewnia bardzo dobre przewodzenie prądu, a jego wykonanie z metalu sprawia, że jest to wyrób solidny i odporny na uszkodzenia i uszczerbki mechaniczne. Przeznaczony do mocowania przewodu spawalniczego jako jednego z biegunów źródła prądu z materiałem spawanym. Zakończenie zacisku wykonane zostało z miedzianych końcówek. Mocowany jest do jednej ze szczęk przy pomocy połączenia śrubowego.",
    category: "zacisk",
    price: 18.00,
    image: "./img/zacisk08-200.jpg",
},
{
    id: 3,
    name: "Zacisk Rhinoweld GC09-00-00-300 300 A",
    description: "Zacisk kleszczowy zapewnia bardzo dobre przewodzenie prądu, a jego wykonanie z metalu sprawia, że jest to wyrób solidny i odporny na uszkodzenia i uszczerbki mechaniczne.",
    category: "zacisk",
    price: 24.00,
    image: "./img/zacisk09-300.jpg",
    status: "Promocja",
    sale: true,
    saleAmount: 2, 
},
{
    id: 4,
    name: "Zacisk Rhinoweld GC07-00-00-600 600 A",
    description: "Zacisk kleszczowy zapewnia bardzo dobre przewodzenie prądu, a jego wykonanie z metalu sprawia, że jest to wyrób solidny i odporny na uszkodzenia i uszczerbki mechaniczne. Przeznaczony do mocowania przewodu spawalniczego jako jednego z biegunów źródła prądu z materiałem spawanym. Zakończenie zacisku wykonane zostało z miedzianych końcówek. Mocowany jest do jednej ze szczęk przy pomocy połączenia śrubowego.",
    category: "zacisk",
    price: 24.00,
    image: "./img/zacisk07-300.jpg",
},
{
    id: 5,
    name: "SZYBKA OCHRONNA POLIWĘGLANOWA 90X110",
    description: "Szybka ochronna wykonana z najwyższej jakości poliwęglanu. Służy do ochrony filtrów w tarczach i przyłbicach spawalniczych. Wysoka jakość materiału zapewnia doskonałą ochronę oraz widoczność co przyczynia się do zwiększenia komfortu użytkowania.",
    category: "szybka",
    price: 1.85,
    image: "./img/szybka-90-110.jpg",
    status: "Nowość",
},
{
    id: 6,
    name: "Wentylator Sherman 12038 FZY BT do spawarki",
    description: "Wentylator firmy Sherman stosowany jest jako część zamienna do urządzeń spawalniczych firm krajowych i zagranicznych.",
    category: "wentylator",
    price: 48,
    image: "./img/wentylator-12038.jpg",
    status: "Nowość",
    sale: false,
},
]